POST http://127.0.0.1:5000/highscore
Content-Type: application/json

{
  "username": "max3",
  "score": "56"
}

<> 2022-05-29T202302.200.html


###

POST http://127.0.0.1:5000/highscore
Content-Type: application/json

{
  "username": "max3",
  "score": "156"
}

<> 2022-05-29T202308.200.html
###

GET http://127.0.0.1:5000/highscore/max3
Accept: application/json

<> 2022-05-29T202309.200.html
<> 2022-05-29T202305.200.html

###
GET http://127.0.0.1:5000/highscore
Accept: application/json

###
