POST http://127.0.0.1:5000/highscore
Content-Type: application/json

{
  "username": "max3",
  "score": "56"
}

###

POST http://127.0.0.1:5000/highscore
Content-Type: application/json

{
  "username": "max3",
  "score": "156"
}

###

GET http://127.0.0.1:5000/highscore/max3
Accept: application/json

###

GET http://127.0.0.1:5000/highscore
Accept: application/json

###

GET http://127.0.0.1:5000/highscore?start=2&count=2
Accept: application/json

###
